name: flutter_recipe_app_course
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.8.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_serializable: ^6.9.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
  fonts:
   - family: Poppins
     fonts:
       - asset: assets/font/Poppins-Regular.ttf
       - asset: assets/font/Poppins-Bold.ttf
         weight: 700

